//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salesftp
{
    using LINQtoCSV;
    using System;
    using System.Collections.Generic;
    
    public partial class SigmaFR
    {
        [CsvColumn(FieldIndex = 1)]
        public string HBSucst { get; set; }
        [CsvColumn(FieldIndex = 2)]
        public string SigmaCust { get; set; }
        [CsvColumn(FieldIndex = 3)]
        public string Company { get; set; }
        [CsvColumn(FieldIndex = 4, CanBeNull = true)]
        public Nullable<int> Invno { get; set; }
        [CsvColumn(FieldIndex = 5, CanBeNull = true)]
        public Nullable<System.DateTime> Invdte { get; set; }
        [CsvColumn(FieldIndex = 6)]
        public int Ornum { get; set; }
        [CsvColumn(FieldIndex = 7)]
        public string HBitem { get; set; }
        [CsvColumn(FieldIndex = 8)]
        public string SigmaItem { get; set; }
        [CsvColumn(FieldIndex = 9)]
        public string Descrip { get; set; }
        [CsvColumn(FieldIndex = 10)]
        public string Ordnum { get; set; }
        [CsvColumn(FieldIndex = 11)]
        public string Ponum { get; set; }
        [CsvColumn(FieldIndex = 12, CanBeNull = true)]
        public Nullable<decimal> Weight { get; set; }
        [CsvColumn(FieldIndex = 13, CanBeNull = true)]
        public Nullable<decimal> Qtyord { get; set; }
        [CsvColumn(FieldIndex = 14, CanBeNull = true)]
        public Nullable<decimal> Qtyshp { get; set; }
        [CsvColumn(FieldIndex = 15, CanBeNull = true)]
        public Nullable<decimal> Price { get; set; }
        [CsvColumn(FieldIndex = 16, CanBeNull = true)]
        public Nullable<decimal> Fdisamt { get; set; }
        [CsvColumn(FieldIndex = 17, CanBeNull = true)]
        public Nullable<decimal> Totdisc { get; set; }
        [CsvColumn(FieldIndex = 18, CanBeNull = true)]
        public Nullable<decimal> Extprice { get; set; }
        [CsvColumn(FieldIndex = 19, CanBeNull = true)]
        public Nullable<decimal> Extwt { get; set; }
        [CsvColumn(FieldIndex = 20, CanBeNull = true)]
        public Nullable<decimal> Cost { get; set; }
        [CsvColumn(FieldIndex = 21, CanBeNull = true)]
        public Nullable<decimal> ExtCost { get; set; }
    }
}
